version: '3'
services:
  mysql:
    image: mysql:8.0.20
    container_name: ${MYSQL_HOST}
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ../mysql:/var/lib/mysql
    networks:
      - shop
  symfony:
    container_name: php-fpm
    build:
      context: ../
      dockerfile: ./docker/php-fpm/Dockerfile
      args:
        TIMEZONE: ${PHP_TIMEZONE}
    #entrypoint: ["sh", "/var/www/app/entrypoint.sh"]
    volumes:
      - ../app:/var/www/app
    environment:
      - APP_ENV
      - APP_SECRET
      - DATABASE_URL
    ports:
      - ${PHP_PORT}:9001
    depends_on:
      - mysql
    networks:
      - shop
  nginx:
    build:
      context: ./nginx
    volumes:
      - ../app/public:/var/www/app/public
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - mysql
      - symfony
    networks:
      - shop

networks:
  shop: